image:
  # -- Respository of the image.
  repository: ghcr.io/ashwinath/money-tracker-telegram
  # -- Image pull policy in Kubernetes
  pullPolicy: Always
    # -- Override this value for the desired image tag
  tag: latest

replicas: 1
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
# -- Resources requests and limits for the application
resources: {}
nodeSelectors: {}

config:
  # -- Telegram API key, must be filled in.
  apiKey: <telegram bot API key here>
  # -- Telegram username handle, must be filled in.
  allowedUser: <your telegram username>
  # -- Enable debug logging
  debug: false

service:
  port: 80

postgresql:
  primary:
    persistence:
      # -- Persist Postgresql data in a Persistent Volume Claim 
      enabled: true
  auth:
    # -- Password for postgresql database, highly recommended to change this value
    postgresPassword: password
