apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "money-tracker-telegram.fullname" . }}
  labels:
    {{- include "money-tracker-telegram.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "money-tracker-telegram.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "money-tracker-telegram.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - ./money-tracker-telegram
          - -config=/etc/config/config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: /etc/config/
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-config
