apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "money-tracker-telegram.fullname" . }}
  labels:
    {{- include "money-tracker-telegram.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "money-tracker-telegram.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "money-tracker-telegram.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:15.2
        command: ['sh', '-c', 
          'until pg_isready -h {{ .Release.Name}}-postgresql -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - ./money-tracker-telegram
          - -config=/etc/config/config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: /etc/config/
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-config
